#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "(deploy) Vrtualenv is activated by : $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate"
source $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate

echo "(deploy) Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py migrate --noinput

echo "(deploy) Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py collectstatic --noinput
